# This file was automatically generated by generate_scp_ou_structure_and_imports.py and may require manual review
    
import {
  to = module.nodeepracer.aws_organizations_policy_attachment.attach_scp["381491898007"]
  id = "381491898007:p-93aknt6d"
}
