{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "DenyPrivilegeVPCEC2Actions",
            "Effect": "Deny",
            "Action": [
                "ec2:AcceptTransitGateway*",
                "ec2:AcceptVpcPeeringConnection",
                "ec2:AssociateTransitGateway*",
                "ec2:AttachInternetGateway",
                "ec2:AttachVpnGateway",
                "ec2:AuthorizeClientVpnIngress",
                "ec2:CreateCarrierGateway",
                "ec2:CreateClientVpnEndpoint",
                "ec2:CreateClientVpnRoute",
                "ec2:CreateCustomerGateway",
                "ec2:CreateInternetGateway",
                "ec2:CreateNatGateway",
                "ec2:CreateTransitGateway*",
                "ec2:CreateTransitGatewayVpcAttachment",
                "ec2:CreateVpcEndpoint*",
                "ec2:CreateVpcPeeringConnection",
                "ec2:CreateVpnConnection",
                "ec2:CreateVpnConnectionRoute",
                "ec2:CreateVpnGateway",
                "ec2:DeleteClientVpnEndpoint",
                "ec2:DeleteClientVpnRoute",
                "ec2:DeleteInternetGateway",
                "ec2:DeleteNatGateway",
                "ec2:DeleteTransitGateway*",
                "ec2:DeleteVpcEndpoint",
                "ec2:DeleteVpcPeeringConnection",
                "ec2:DeleteVpnConnection",
                "ec2:DeleteVpnConnectionRoute",
                "ec2:DeleteVpnGateway",
                "ec2:DeregisterTransitGateway*",
                "ec2:DetachInternetGateway",
                "ec2:DetachVpnGateway",
                "ec2:DisableTransitGatewayRouteTablePropagation",
                "ec2:DisassociateClientVpnTargetNetwork",
                "ec2:DisassociateTransitGateway*",
                "ec2:EnableTransitGatewayRouteTablePropagation",
                "ec2:EnableVgwRoutePropagation",
                "ec2:EnableVpcClassicLinkDnsSupport",
                "ec2:ExportTransitGatewayRoutes",
                "ec2:ModifyClientVpnEndpoint",
                "ec2:ModifyTransitGateway*",
                "ec2:ModifyVpcEndpoint",
                "ec2:ModifyVpcPeeringConnectionOptions",
                "ec2:ModifyVpnConnection",
                "ec2:RegisterTransitGatewayMulticast*",
                "ec2:RejectTransitGateway*",
                "ec2:RejectVpcEndpointConnections",
                "ec2:RejectVpcPeeringConnection",
                "ec2:ReplaceTransitGatewayRoute",
                "ec2:RevokeClientVpnIngress",
                "ec2:TerminateClientVpnConnections"
            ],
            "Resource": "*",
            "Condition": {
                "ArnNotLike": {
                    "aws:PrincipalARN": [
                        "arn:aws:iam::${master_account_id}:role/AWSAFTService",
                        "arn:aws:iam::*:role/AWSControlTowerExecution",
                        "arn:aws:iam::*:role/AWSAFTExecution",
                        "arn:aws:iam::*:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_<PERMISSION SET NAME>_*",
                        "arn:aws:iam::*:role/<ALL PIPELINE ROLES PLACEHOLDER>"
                    ]
                }
            }
        },
        {
            "Sid": "PreventNetworkIngressEgressforNonNetworkOU",
            "Effect": "Deny",
            "Action": [
                "directconnect:Accept*",
                "directconnect:Allocate*",
                "directconnect:Associate*",
                "directconnect:Confirm*",
                "directconnect:Create*",
                "directconnect:Delete*",
                "directconnect:Update*",
                "directconnect:Disassociate*",
                "directconnect:Start*",
                "directconnect:Stop*",
                "directconnect:Untag*",
                "globalaccelerator:Deny*",
                "globalaccelerator:Add*",
                "globalaccelerator:Allow*",
                "globalaccelerator:Advertise*",
                "globalaccelerator:Deprovision*",
                "globalaccelerator:Create*",
                "globalaccelerator:Delete*",
                "globalaccelerator:Provision*",
                "globalaccelerator:Remove*",
                "globalaccelerator:Update*",
                "globalaccelerator:Withdraw*",
                "globalaccelerator:Untag*",
                "cloudfront:Publish*",
                "cloudfront:Test*",
                "directconnect:Allocate*",
                "cloudfront:Associate*",
                "cloudfront:Create*",
                "cloudfront:Delete*",
                "cloudfront:Update*",
                "cloudfront:Untag*",
                "ec2:AttachInternetGateway",
                "ec2:CreateInternetGateway",
                "ec2:CreateEgressOnlyInternetGateway",
                "ec2:CreateVpcPeeringConnection",
                "ec2:AcceptVpcPeeringConnection",
                "ec2:ModifyVpcPeeringConnectionOptions",
                "ec2:RejectVpcPeeringConnection"
            ],
            "Resource": "*"
        }
    ]
}
